export const APP_CONTEXT_TYPES = {
  START_LOADING: 'START_LOADING',
  STOP_LOADING: 'STOP_LOADING',
  ADD_USER: 'STORE_USER',
  DELETE_USER: 'DELETE_USER',
  UPDATE_APP_LANGUAGE: 'UPDATE_APP_LANGUAGE',
};
